runtime: php81  # Specify PHP 8.1 runtime

# URL handling for static files (CSS, JS, and assets)
handlers:
  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /assets
    static_dir: assets

# URL handling for PHP scripts
  - url: /php/schedule_tour.php
    script: php/schedule_tour.php

  - url: /php/send_location.php
    script: php/send_location.php

  - url: /php/submit_contact.php
    script: php/submit_contact.php

  - url: /php/submit_dietary_needs.php
    script: php/submit_dietary_needs.php

# Catch-all routing for dynamic content (other PHP files)
  - url: /.*
    script: auto

# Database settings (Cloud SQL connection)
env_variables:
  MYSQL_DSN: "mysql:dbname=blady_world_db;host=/cloudsql/quick-glow-438420-v7:us-east4:bladys-world-sql"
  MYSQL_USER: "cameronroy"
  MYSQL_PASSWORD: ",@zjnHqAV+}9gpj4"

# Ensure Cloud SQL instance is accessible
beta_settings:
  cloud_sql_instances: quick-glow-438420-v7:us-east4:bladys-world-sql